FROM ubuntu:16.04
MAINTAINER DrTrigon <dr.trigon@surfeu.ch>

# LABEL author.user1="Abdeali JK <abdealikothari@gmail.com>" \
#       author.user2="DrTrigon <dr.trigon@surfeu.ch>"

# Initial update
RUN apt-get -y update

# Basic packages
RUN apt-get install -y \
  build-essential \
  make \
  git

# Pip - install latest version so that wheels are used
RUN apt-get install -y python-pip && \
  pip install -U pip

# Packages for setup
RUN apt-get install -y pkg-config

# ExifTool
RUN apt-get install -y exiftool

# OpenCV
RUN apt-get install -y python-opencv opencv-data

# Image Magick / wand
RUN apt-get install -y libmagickwand-dev python-dev

# avprobe / ffprobe
RUN apt-get install -y libav-tools

# ZXing
#RUN apt-get install -y openjdk-7-jre
RUN apt-get install -y openjdk-8-jre

# Dlib
RUN apt-get install -y cmake libboost-python-dev python-dev

# ZBar
RUN apt-get install -y libzbar-dev python-dev

# Add the repository
RUN git clone https://github.com/AbdealiJK/file-metadata.git /opt/file-metadata

# Test requirements
RUN pip install -r /opt/file-metadata/test-requirements.txt

# Install package
RUN pip install /opt/file-metadata --upgrade

# Temporary bugfix until gone upstream to file-metadata:master
ADD https://gist.githubusercontent.com/drtrigon/b7d367514745715fff332b652349f222/raw/dba339bedb0b0e939e62652aa29446a078fda9a6/file-metadata.diff /opt/file-metadata/
RUN cd /opt/file-metadata/ && patch -p0 < file-metadata.diff
