FROM ubuntu:16.04
MAINTAINER DrTrigon <dr.trigon@surfeu.ch>

# LABEL author.user1="Abdeali JK <abdealikothari@gmail.com>" \
#       author.user2="DrTrigon <dr.trigon@surfeu.ch>"

# Initial update
RUN apt-get -y update

# Pip - install latest version so that wheels are used
RUN apt-get install -y python-pip && \
  pip install -U pip

# Packages for setup
RUN apt-get install -y pkg-config

# ExifTool
RUN apt-get install -y exiftool

# OpenCV
RUN apt-get install -y python-opencv opencv-data

# Image Magick / wand
RUN apt-get install -y libmagickwand-dev

# avprobe / ffprobe
RUN apt-get install -y libav-tools

# ZXing
RUN apt-get install -y default-jre

# Dlib
RUN apt-get install -y cmake libboost-python-dev python-dev

# ZBar
RUN apt-get install -y libzbar-dev python-dev

# Add the repository
RUN apt-get install -y git
RUN git clone https://github.com/pywikibot-catfiles/file-metadata.git /opt/file-metadata

# Test requirements
RUN pip install -r /opt/file-metadata/test-requirements.txt

# Install package
RUN pip install -e /opt/file-metadata --upgrade
